<?php 
    $this->headTitle('GE ThxBox - It\'s so easy to say Thank You'); 
    $this->headLink()->appendStylesheet('/styles/private.css');
?>
<div id='private-main-container'>
	<div id='public-thxbox-header'>
		<img src="/images/logo_login.png" />
		<h3>It's so easy to say Thank You.</h3>
	</div> 


	<img src="/images/sun-login.png" id='sun-center' />
	<div id='private-set-password-box'>

		<form action='/private/' method='POST' id='private-form'>

			<!-- signup -->
				<div id='signup-box-outer'>
					<div class='input-box'>	
						<div>full name</div>
						<input type='text' id='signup-fullname' name='fullname' />
						<div>email</div>
						<input type='text' id='signup-email' name='email_signup' value='<?php echo $this->email; ?>'  readonly="readonly" style="background: #EEE; color:#999;" />
						<div>password</div>
						<input type='password' id='signup-pass' name='pass_signup' />
						<div><span>birthday</span>&nbsp;<span class="optional">( optional )</span></div>
						
						<div>
							<select class="input-box-select" name="dob_day" id='dob_day'>
								<option value=''>- day -</option>
								<?php for($count=1; $count<=31; $count++): ?>
								<option><?php echo $count; ?></option>
								<?php endfor; ?>
							</select>
							<select class="input-box-select" name="dob_month" id='dob_month'>
								<option value=''>- month -</option>
								<?php foreach($this->month AS $key=>$val): ?>
								<option value='<?php echo $key; ?>'><?php echo $val; ?></option>
								<?php endforeach; ?>
							</select>
						</div>

						<div><span>country</span>&nbsp;<span class="optional">( optional )</span></div>

						<div>
							<select class="input-box-select" name="country" id='country' style="width: 203px;">
								<?php 
									$country = $this->country;												
									foreach($country AS $key=>$val): 
										echo "<option value='".$key."'>".$val."</option>";						
									endforeach;	
								?>
							</select>
						</div>					
					</div>
					<div class="submit-box">	
						<div>
						<input type='checkbox' id='signup-tc' style="vertical-align: middle; " />
						<span class="bold">&nbsp;I agree to the following Terms & Conditions:</span>
						</div>
						<div style="margin: 10px 0;">	
							I understand that this site is not operated by GE
							or any of its subsidiaries, and that it was developed
							by Arcanys for GE GG&O. Only GE employees with
							a valid ge.com email address may signup to this system.
							The information provided will not be used for any
							commercial purposes. You acknowledge that you are
							prodiving your information voluntarily.
						</div>
						
						<div style="float: left;">
							<button class="button-disabled" name="signup" id='signup-button' disabled style="padding: 8px 15px; font-size: 15px;">
								<span>Save and Continue</span>
							</button>
							<img src="/images/loader/loading.gif" id='signup-loader' style="position: relative; top: 3px; left: 5px; display:none;" /> 
						</div>
						<div class='clear'></div>
					</div>
				</div>	
			<!-- end signup -->

			<input type='hidden' name='confirmation_link' value='<?php echo $this->confirmation_link; ?>' />
			<input type='hidden' name='pid' value='<?php echo $this->pid; ?>' />
			
			<!--
			<input type='hidden' name='confirmation_link' value='<?php echo $this->confirmation_link; ?>' />
			<input type='hidden' name='pid' value='<?php echo $this->pid; ?>' />

			<div id='private-textbox-container' class=''>
				<div class='private-error-box'>
					<div class='error-msg-div'>					
						Don't leave any fields blank!					
						<a href='#' class='private-error-close'>&#215;</a>
					</div>	
				</div>	
				<div id='input-box-login'>
					<div>Full Name</div>	
					<input type='text' name='fullname' autocomplete="off" id='fullname'/>
					<div>Password</div>
					<input type='password' name='password' autocomplete="off" id='password'/>
				</div>

				<div>
					<button id="private-submit" class='default'>
						<span>Submit!</span>
					</button>
				</div>
			</div>
			-->
			
		</form>
	</div>

<div id="private-push"></div>
</div>

<div id='private-footer'></div> 

<?php
	$this->headScript()->appendFile('/scripts/private.js');
?>