<?php 
    $this->headTitle('GE ThxBox - It\'s so easy to say Thank You'); 
    $this->headLink()->appendStylesheet('/styles/winner.css');
    /*
    $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Handlee');
    $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Great+Vibes');
    $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Just+Me+Again+Down+Here');
    $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Sunshiney');
    $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Nothing+You+Could+Do');
    $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Delius+Unicase');
	*/
?>

<div id="winner-main-container">
	<div id='winner-detail-box'>
		<div id='winner-detail-box-right'>
			<div class='malgunbd' style='background: #EEE; padding: 10px; width: 300px; height: 200px; margin: 0 auto; border: 1px solid #111; position: relative; top: -20px'>
				

				<?php if($this->anonymous['anonymous']) :?>
				<div>
					<span style='display: block; font-size: 13px; color: #9C4706;' class='malgunbd'>Anonymous</span>
					<span style='letter-spacing: 1px; display: block; font-size: 12px; color: #000;' class='malgunbd'>
						<?php echo $this->data['pretty_date_posted']; ?>
					</span>
				</div>
				<?php else: ?>	
				<img style='margin-right: 5px; vertical-align: bottom; float: left;' src='<?php echo $this->data['avatar_path']?>' />
				<div style='margin-bottom: 10px;'>	
					<span style='font-size: 13px; margin-bottom: 15px; color: #9C4706;' class='malgunbd'>
						<?php echo $this->data['full_name']; ?>
					</span>
					<span style='letter-spacing: 1px; display: block; font-size: 12px; color: #000;' class='malgunbd'>
						<?php echo $this->data['pretty_date_posted']; ?>
					</span>
				</div>	
				<?php endif; ?>
				<?php echo $this->data['message']; ?>
			</div>
			<a href='<?php echo $this->url; ?>' style='position: relative; top: 15px; left: 175px;'>
				<img src='/images/buttons/sign_up_btn.png' />
			</a>
		</div>
	</div>
	
	<div id='winner-content-img'>
		<div>		
		<img src="/images/page3-img-big.png" /> 
		</div>
	</div>	
</div>