<?php 
    $this->headTitle('GE ThxBox - It\'s so easy to say Thank You');
    $this->headLink()->appendStylesheet('/styles/signup.css');
?>

<div id="login-main-container">

<div id='login-header'>	
	<img src="/images/ge_logo_small.png" style="float: left" />		
	<a href="javascript:void(0)" class="link-active signup right" id='signup'>Sign-up</a>
	<span class="right" style="margin: 0 5px;">|</span>
	<a href="javascript:void(0)" class="link-passive right" id='signin'>Login</a>	
</div>
	
<div id='login-thxbox-header'>
	<img src="/images/logo_login.png" />
	<h3>It's so easy to say Thank You.</h3>
</div> 



<img src="/images/sun-login.png" id='sun-center' />
<div id='login-sun-center'>		
	<!--<img src="/images/ge-logo.png" id='login-ge-logo' />-->
	<form action='login' method='POST' id='login-form'> 

	<div id='login-box'>	
		<div id='input-box' class='input-box'>
			<div id='input-box-login'>
				<div>GE-email</div>	
				<input type='text' id='login-email' name='email' placeHolder='Please enter your GE-email' />
				<div>Password</div>
				<input type='password' id='login-pass' name='pass' placeHolder='Enter your password' />
			</div>
		</div>	
		<div class="login-submit-box">
			<div id='login-box-submit'>
				<a href='/recover'>Password help?</a>
				<button type='submit' class="button-blue right login_span_btn" style="padding: 5px 20px 6px;" name="login" >
					Log in
				</button>				
			</div>
			<div class='clear'></div>
		</div>	

	</div>
	</form>

	<div id='signup-box'>			
		<div id='signup-box-inner' class='input-box'>			
			<div id='input-box-signup'>	
				<div>full name</div>
				<input type='text' id='signup-fullname' name='fullname' />
				<div>email</div>
				<input type='text' id='signup-email' name='email_signup' />
				<div>password</div>
				<input type='password' id='signup-pass' name='pass_signup' />
				<div><span>birthday</span>&nbsp;<span class="optional">( optional )</span></div>


				
				<div>
					<select class="input-box-select" name="dob_day" id='dob_day'>
						<option value=''>- day -</option>
						<?php for($count=1; $count<=31; $count++): ?>
						<option><?php echo $count; ?></option>
						<?php endfor; ?>
					</select>
					<select class="input-box-select" name="dob_month" id='dob_month'>
						<option value=''>- month -</option>
						<?php foreach($this->month AS $key=>$val): ?>
						<option value='<?php echo $key; ?>'><?php echo $val; ?></option>
						<?php endforeach; ?>
					</select>
				</div>

				<div><span>country</span>&nbsp;<span class="optional">( optional )</span></div>

				<div>
					<select class="input-box-select" name="country" id='country' style="width: 203px;">
						<?php 
							$country = $this->country;												
							foreach($country AS $key=>$val): 
								echo "<option value='".$key."'>".$val."</option>";						
							endforeach;	
						?>
					</select>
				</div>
				
			</div>
		</div>	
			
		<div class="login-submit-box">
			<div id='signup-box-submit'>	
				<div>
				<input type='checkbox' id='signup-tc' style="vertical-align: middle; " />
				<span class="bold">&nbsp;I agree to the following Terms & Conditions:</span>
				</div>
				<div style="margin: 10px 0;">	
					I understand that this site is not operated by GE
					or any of its subsidiaries, and that it was developed
					by Arcanys for GE GG&O. Only GE employees with
					a valid ge.com email address may signup to this system.
					The information provided will not be used for any
					commercial purposes. You acknowledge that you are
					prodiving your information voluntarily.
				</div>
				
				<div style="float: left;">
					<button class="button-disabled" name="signup" id='signup-button' disabled style="padding: 8px 15px; font-size: 15px;">
						<span>Save and Continue</span>
					</button>
					<img src="/images/loader/loading.gif" id='signup-loader' style="position: relative; top: 3px; left: 5px; display:none;" /> 
				</div>
				<div class='clear'></div>
			</div>			
		</div>	
	</div>

</div>

<div id="login-push"></div>
</div>

<div id='login-footer'></div> 

<?php
	$this->headScript()->appendFile('/scripts/login.js');
	$this->headScript()->captureStart();
?>
	var whichIsCurrentlyDisplayed = 'signup';			
<?php $this->headScript()->captureEnd(); ?>