<?php echo $this->doctype()."\n"; ?>


<!--[if IE 8]> <html class="ie8"> <![endif]-->
<!--[if !IE]><!--> <html class="noIE"> <!--<![endif]-->

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=8" />
<link href="/images/favicon.png" rel="shortcut icon" type="image/x-icon" />

<?php echo $this->headTitle()."\n"; ?>
<link href="/styles/global.css" media="screen" rel="stylesheet" type="text/css" >
<?php echo $this->headLink()."\n"; ?>

<script src="https://www.google.com/jsapi" type="text/javascript"></script>
<script type="text/javascript">
google.load("jquery", "1.7.1");
google.load("jqueryui", "1.8.17");
</script>  

<?php echo $this->headScript()."\n"; ?>
</head>

<body>
		
		<?php echo $this->layout()->content ?>
		
</body>
</html>